select ABS(-100) from dual;

select ABS(-6) from dual;

select FLOOR(2345.78) FROM DUAL;

SELECT GREATEST(23,67,90,123,78,50) FROM DUAL;

SELECT LEAST(34, 21,67,11,89,9) FROM DUAL;

SELECT LENGTH('RAJESHWARI') FROM DUAL;

SELECT LENGTH(17245637) FROM DUAL;

SELECT SQRT(16) FROM DUAL;

SELECT SQRT(99) FROM DUAL;

SELECT POWER(2,4) FROM DUAL;

SELECT POWER(2,10) FROM DUAL;

SELECT power(2,10) FROM DUAL;

SELECT ROUND(5.86) FROM DUAL;

SELECT ROUND(1001.6) FROM DUAL;

SELECT ROUND(1001.3) FROM DUAL;

SELECT SIN(90) FROM DUAL;

SELECT COS(45) FROM DUAL;

SELECT TAN(30) FROM DUAL;

SELECT TAN(90) FROM DUAL;

SELECT TAN(180) FROM DUAL;

SELECT SIGN(-128) FROM DUAL;

SELECT SIGN(10) FROM DUAL;

SELECT SIGN(0) FROM DUAL;

SELECT LN(100) FROM DUAL;

SELECT LN(10) FROM DUAL;

SELECT LOG(10,100) FROM DUAL;

SELECT LOG(100,10) FROM DUAL;

SELECT MOD(4,3) FROM DUAL;

SELECT MOD(4,2) FROM DUAL;

SELECT EXP(2) FROM DUAL;

SELECT EXP(-2) FROM DUAL;

SELECT EXP(0) FROM DUAL;


SELECT CURRENT_DATE FROM DUAL;

SELECT EXTRACT(YEAR FROM SYSDATE()) FROM DUAL;

SELECT EXTRACT(DAY FROM SYSDATE()) FROM DUAL;

SELECT EXTRACT(MONTH FROM SYSDATE()) FROM DUAL;

SELECT SYSDATE() FROM DUAL;

select ascii('t') from dual;

select ascii('a') from dual;

select ascii('A') from dual;

select ascii('Z') from dual;

select ascii('z') from dual;

SELECT UPPER('blah blah') from dual;

select LOWER('welcome to dbms lab') from dual;

select LOWER('WELCOME TO DBMSLAB') from dual;

SELECT REPLACE('HELLO','H','K') FROM DUAL;

SELECT REPLACE('COMPUTER','C','K') FROM DUAL;

SELECT REPLACE('HELLO','L','A') FROM DUAL;

SELECT TRIM('A' FROM 'ANACONDA') FROM DUAL;

SELECT TRIM(LEADING 'A' FROM 'ANACONDA');

SELECT TRIM(LEADING 'A' FROM 'ANIL');

SELECT TRIM(TRAILING 'A' FROM 'ANITA');

SELECT TRIM(TRAILING 'A' FROM 'ANACONDA');
